### ISSUE TITLE
Crash when biomemap is nil (subterrane does not work with singlenode)

### ISSUE THREAD

**Issue by Poikilos** [FaceDeer/subterrane#5]
Copied from <https://github.com/FaceDeer/minetest-caverealms/issues/2> since seems to be a subterrane issue:
I am using experimental mapgen (mg). I'm not sure if this is an mg issue, caverealms issue, or subterrane issue--I looked at the line in question, which uses biomemap, a local variable which should contain the result of `minetest.get_mapgen_object("biomemap")`. I don't know enough to know why `get_mapgen_object` would ever return nil after looking up its meaning. If I restart the server, it works for a while, but when trying to dig deeper in a certain location the server crashes. Apparently the problem happens when a caverealm generates.

Seed: BagEnd
Location: `/teleport 17,-566,98`
MapGen: v7
minetest version: 0.5.0-dev (~2018-02-21)
mapgen mods:
* mg
* subterrane
* caverealms (FaceDeer's fork of caverealms which is integrated with mapgen v7's perlin noise and uses subterrane)
* magma_conduits
* minor mapgen mods: moreores, techic, ... for others see <https://github.com/expertmm/EnlivenMinetest/blob/master/etc/game-install-ENLIVEN>

2018-02-23 19:37:29: ACTION[Main]: [playereffects] Server shuts down. Rescuing data into playereffects.mt
2018-02-23 19:37:29: ACTION[Main]: [playereffects] Wrote playereffects data into /home/owner/.minetest/worlds/FCAWorldB/playereffects.mt.
2018-02-23 19:37:30: ACTION[Main]: [fishing] Server shuts down. saving trophies table
2018-02-23 19:37:31: ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'caverealms' in callback environment_OnGenerated(): ...al/share/minetest/games/ENLIVEN/mods/subterrane/init.lua:181: attempt to index local 'biomemap' (a nil value)
2018-02-23 19:37:31: ERROR[Main]: stack traceback:
2018-02-23 19:37:31: ERROR[Main]: 	...al/share/minetest/games/ENLIVEN/mods/subterrane/init.lua:181: in function <...al/share/minetest/games/ENLIVEN/mods/subterrane/init.lua:116>
2018-02-23 19:37:31: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:420: in function </usr/local/share/minetest/builtin/game/register.lua:400>

**Comment by Poikilos** [comment]
I looked into it further after comments from since posting the issue on caverealms. I tried the following change:
```lua
                                        local biome_name = nil
                                        local biome = nil
                                        if biomemap ~= nil then
                                                biome_name = subterrane.biome_ids[biomemap[index_2d]]
                                                biome = minetest.registered_biomes[biome_name]
                                        --else using a singlenode mapgen
                                        end
```
(each time biomemap is used)


However, as I suspected (since all of the other code is conditional on `biome` being true/truthy), the result is a huge empty cube underground (`/teleport 11,-708,130` with seed BagEnd with mg and the mods mentioned earlier installed) instead of a caverealm. Can you offer a solution, that neither crashes nor prevents generating the caverealm?

:edit: The empty cube was caused by the crash, not by the code change. I made a new world with the same seed and the area was generated but there was no caverealm nearby, nor anywhere that I could tell after some searching with fast,fly,noclip.

**Comment by redblade7** [comment]
Where are you putting this code @poikilos ? I was having caverealms crashes and switched over to FaceDeer's fork, and am now having this crash instead. I've reported it on the forum, but no answer. I'm using 0.4.17.1 with v6.

**Comment by Poikilos** [comment]
I just tried the code on my server, then reverted the change it when it didn't make it work (then I switched back to minetest's own mapgen which seems to be the only one compatible with caverealms).

**Comment by FaceDeer** [comment]
Sorry about kind of drifting away from Minetest modding for a bit there, real life and all that. But the project at work that's been devouring all my spare time is concluding and I'm getting back to this now, and in the process of messing around I have done a *major* renovation of subterrane's code. Should have this issue fixed soon (it's already fixed in the branch I'm working in, but I need to update caverealms to use the new version - all my work has been done with dfcaverns so far).

**Comment by FaceDeer** [comment]
I've merged in the branch that should fix this. Lots of "if not nil" checks scattered around now.
