### ISSUE TITLE
Crash - attempt to index local 'stalagmite_id' (a boolean value)

### ISSUE THREAD

**Issue by ghost** [FaceDeer/subterrane#8]
```
ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'dfcaverns' in callback environment_OnGenerated(): .../subterrane/features.lua:28: attempt to index local 'stalagmite_id' (a boolean value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	.../subterrane/features.lua:28: in function 'stalagmite'
ERROR[Main]: 	.../dfcaverns/biomes.lua:31: in function '_subterrane_cave_floor_decor'
ERROR[Main]: 	...subterrane/init.lua:479: in function <.../subterrane/init.lua:406>
ERROR[Main]: 	.../minetest/bin/../builtin/game/register.lua:412: in function <.../minetest/bin/../builtin/game/register.lua:392>
```

**Comment by FaceDeer** [comment]
Rrr. This is another result of the change I made when I pulled the stalactite nodes out of subterrane to allow mods to define their own. You're using the new version of subterrane with an old version of dfcaverns, I take it?

I think I can make the versions cross-compatible. Wish there was a standard way of putting version flags on these things.

**Comment by FaceDeer** [comment]
Okay, I believe I've fixed it. The new stalagmite function is now called "small_stalagmite" and the old one is defined in legacy.lua so if you want to use the old dfcaverns with the new subterrane it should work.

You'll need to update dfcaverns to the latest version if you want to use the new dfcaverns, though, since it needs to call small_stalagmite now.

**Comment by ghost** [comment]
After that you wrote the first reply I've downloaded the latest version of dfcaverns (master branch) and subterrane (sunless sea branch); I had the same issue.

Now I'm going to do the same, download the latest dfcaverns master branch and subterrane's latest development branch; I'll tell you in a few how it goes the test.

--EDIT
Ok, I've downloaded the latest subterrane master branch AND dfcaverns-sunless-sea; all clear, no more issues :)) thanks!


I must stick to Minetest Game 0.4.16 for my game: v1.x was based on 0.4.17-dev, then I realized that a rolling release as base was a nightmare.
